crex424/EasyAppointmentManager

EasyAppointmentManager/Models/Customer.cs
EasyAppointmentManager/Models/Customers.cs

Created a class for Customers with required fields.
Added documentation and basic data annotation.
Closes #2

TungKim - issue #2 - Create customers class

---

EasyAppointmentManager/Models/Specialty.cs

Created a class for Specialties with required fields.
Added documentation and basic data annotation.
Closes #5

TungKim - issue #5 - Created a class of Specialty

---

EasyAppointmentManager/Models/Doctor.cs

Closes #17 
Removed required annotation from PlaceOfWork field. Added PhoneNumber and Gender Field. Added Error message annotation to all required fields. Display data annotation also added for all fields

Made improvements to class. 

---

EasyAppointmentManager/Models/Location.cs

Closes #6 
Created Location class with required fields. Added new fields to better store/separate the Location's address, city, and zipcode.

Created Location Class

---

EasyAppointmentManager/Models/Fee.cs

Closes #7 
Created fields with documentation, and data annotation for Fee class.

Created Fee class with required fields and data annotation

---

EasyAppointmentManager/Models/Clinic.cs

Tungkim issue#18 create clinic class

---

EasyAppointmentManager/Controllers/CustomersController.cs
EasyAppointmentManager/Data/ApplicationDbContext.cs
EasyAppointmentManager/Models/Customer.cs
EasyAppointmentManager/Models/CustomerCatalogViewModel.cs
EasyAppointmentManager/Views/Customers/Create.cshtml
EasyAppointmentManager/Views/Customers/Delete.cshtml
EasyAppointmentManager/Views/Customers/Details.cshtml
EasyAppointmentManager/Views/Customers/Edit.cshtml
EasyAppointmentManager/Views/Customers/Index.cshtml
EasyAppointmentManager/Views/Customers/Index_CatalogView.cshtml
EasyAppointmentManager/Views/Shared/_Layout.cshtml

Created CustomersController and Views for Customers
Added migration
Closes #8

TungKim Issue#8 Created CustomersController with Views

---

EasyAppointmentManager/Views/Customers/Index.cshtml

Change Gender display from True/False to Male/Female in Index view

---

EasyAppointmentManager/Controllers/Doctor.cs
EasyAppointmentManager/Data/ApplicationDbContext.cs
EasyAppointmentManager/Models/Doctor.cs

Closes #9 
Created Doctor Controller with all functionalities included. Will not work until database has been figured out/created.
Let me know if documentation is no satisfactory.

Created DoctorController

---

EasyAppointmentManager/Models/Service.cs

Closes #31 
Refactored Fee class into Service class with fields changed to fit such object. Unsure what data type to have ServiceTime as so defaulted to string, suggestions are welcome.

Refactor Fee class to Service

---

EasyAppointmentManager/Controllers/DoctorsController.cs

Closes #39 
Renamed DoctorController to DoctorsController.

Renamed DoctorController to DoctorsController

---

EasyAppointmentManager/Controllers/LocationsController.cs
EasyAppointmentManager/Data/ApplicationDbContext.cs
EasyAppointmentManager/Views/Locations/Create.cshtml
EasyAppointmentManager/Views/Locations/Delete.cshtml
EasyAppointmentManager/Views/Locations/Details.cshtml
EasyAppointmentManager/Views/Locations/Edit.cshtml
EasyAppointmentManager/Views/Locations/Index.cshtml

Closes #11 
Created LocationsController with the functions Create/Edit/Delete/Details.
Created views for function's Create/Update/Delete/Details as well as index

Created LocationController with needed views such as Index/Create/Edit/Details/Delete

---

EasyAppointmentManager/Views/Doctors/Create.cshtml
EasyAppointmentManager/Views/Doctors/Delete.cshtml
EasyAppointmentManager/Views/Doctors/Details.cshtml
EasyAppointmentManager/Views/Doctors/Edit.cshtml
EasyAppointmentManager/Views/Doctors/Index.cshtml

Closes #38 
Created views for DoctorController to allow use of DoctorController functionality.

Create views for the DoctorController's functions

---

EasyAppointmentManager/Controllers/DoctorsController.cs
EasyAppointmentManager/Data/Migrations/20230423165615_AddedClinic.Designer.cs
EasyAppointmentManager/Data/Migrations/20230430150514_RefactoredClinic.Designer.cs
EasyAppointmentManager/Data/Migrations/20230501202553_DoctorIDtoDoctorId.Designer.cs
EasyAppointmentManager/Data/Migrations/20230501202553_DoctorIDtoDoctorId.cs
EasyAppointmentManager/Data/Migrations/ApplicationDbContextModelSnapshot.cs
EasyAppointmentManager/Models/Doctor.cs
EasyAppointmentManager/Views/Doctors/Delete.cshtml
EasyAppointmentManager/Views/Doctors/Details.cshtml
EasyAppointmentManager/Views/Doctors/Edit.cshtml
EasyAppointmentManager/Views/Doctors/Index.cshtml

Change DoctorID to DoctorId to follow naming pattern

---

EasyAppointmentManager/Views/Shared/_Layout.cshtml

Added link to Doctors index page

---

EasyAppointmentManager/Data/Migrations/20230423165615_AddedClinic.cs
EasyAppointmentManager/Data/Migrations/20230430150514_RefactoredClinic.cs
EasyAppointmentManager/Data/Migrations/20230501202553_DoctorIDtoDoctorId.cs
EasyAppointmentManager/Data/Migrations/ApplicationDbContextModelSnapshot.cs

Closes #55 
I fixed the error.

Fixed DB error

---

EasyAppointmentManager/Models/TimeSlot.cs
EasyAppointmentManager/Program.cs

Created DatabaseSeeder class with SeedData() method to automatically populate TimeSlots of all doctors with 1-hour blocks from 8:00 10 16:00 with TimeSlotStatus "Available".
Works perfectly on my end. Please check it out and merge it if you think it's good enough.
Thank you very much!
Closes #63

Added code to populate TimeSlot data for doctors with status Available

---

EasyAppointmentManager/Controllers/DoctorsController.cs
EasyAppointmentManager/Models/Doctor.cs
EasyAppointmentManager/Views/Doctors/Create.cshtml

Closes #57 
Created dropdown functionality for Specialty and Clinc.
Cannot work of dropdown functionality for Services until Services is connected to Doctor

create refactor for drop-down of Specialty and Clinic

---

EasyAppointmentManager/Controllers/DoctorsController.cs
EasyAppointmentManager/Models/Doctor.cs
EasyAppointmentManager/Views/Doctors/Index.cshtml

Closes #74 
Closes #73 
Index now displays a Doctor's Specialty and the clinic they work at.
I also removed some information from index to display only in details page since that information is not as important as some of the other information on the index page. Let me know whether you want this change to be permanent or reversed.

Added functionality for index to display Doctor's Specialty and the Clinic they work at.

---

EasyAppointmentManager/Controllers/DoctorsController.cs
EasyAppointmentManager/Models/Doctor.cs
EasyAppointmentManager/Views/Doctors/Delete.cshtml

Closes #73 
Closes #72 
Delete page now displays chosen doctor's specialty and clinic.

Delete page now displays chosen doctor's specialty and clinic

---

.gitignore
EasyAppointmentManager/Controllers/DoctorsController.cs
EasyAppointmentManager/Models/Doctor.cs
EasyAppointmentManager/Views/Clinics/Create.cshtml
EasyAppointmentManager/Views/Clinics/Delete.cshtml
EasyAppointmentManager/Views/Clinics/Details.cshtml
EasyAppointmentManager/Views/Clinics/Edit.cshtml
EasyAppointmentManager/Views/Clinics/Index.cshtml
EasyAppointmentManager/Views/Customers/Create.cshtml
EasyAppointmentManager/Views/Customers/Delete.cshtml
EasyAppointmentManager/Views/Customers/Details.cshtml
EasyAppointmentManager/Views/Customers/Edit.cshtml
EasyAppointmentManager/Views/Customers/Index.cshtml
EasyAppointmentManager/Views/Doctors/Create.cshtml
EasyAppointmentManager/Views/Doctors/Delete.cshtml
EasyAppointmentManager/Views/Doctors/Details.cshtml
EasyAppointmentManager/Views/Doctors/Edit.cshtml
EasyAppointmentManager/Views/Doctors/Index.cshtml
EasyAppointmentManager/Views/Specialties/Create.cshtml
EasyAppointmentManager/Views/Specialties/Delete.cshtml
EasyAppointmentManager/Views/Specialties/Details.cshtml
EasyAppointmentManager/Views/Specialties/Edit.cshtml
EasyAppointmentManager/Views/Specialties/Index.cshtml

Closes #67 
Closes #70  
Closes #71 
Drop-down lists for Specialties, and Clinic on Update page now display correct information.
Index page will now display success messages from CRUD pages.
Details page now displays Specialties and Clinic for doctor. Gender is displayed as a readable format.

Drop-down lists for Update page now display correct information

---

EasyAppointmentManager/Controllers/ClinicsController.cs
EasyAppointmentManager/Views/Clinics/Index.cshtml

The Create feature now sends a success message to index.
The Edit feature now sends a success message to index.
The Delete feature now sends a success message to index.

Clinic index now displays success message for CRUD

---

EasyAppointmentManager/Models/Service.cs
EasyAppointmentManager/Models/TimeSlot.cs

Added comment headers to Class and methods

Tk issue#82 review and document classes and methods

---

EasyAppointmentManager/Views/Home/Index.cshtml

The addition's to the styling is what the home page will look like when the functionality for the appointment class are finished. 
The idea is that if the user has an appointment, then the card with display the details of the appointment of the home page. If they do not have an appointment, then the button to make the appointment will be displayed which will take them to the appointment creation page.

Added styling for home page.

---

EasyAppointmentManager/Models/Doctor.cs
EasyAppointmentManager/Views/Clinics/Create.cshtml
EasyAppointmentManager/Views/Clinics/Delete.cshtml
EasyAppointmentManager/Views/Clinics/Details.cshtml
EasyAppointmentManager/Views/Clinics/Edit.cshtml
EasyAppointmentManager/Views/Clinics/Index.cshtml
EasyAppointmentManager/Views/Customers/Create.cshtml
EasyAppointmentManager/Views/Customers/Delete.cshtml
EasyAppointmentManager/Views/Customers/Edit.cshtml
EasyAppointmentManager/Views/Customers/Index.cshtml
EasyAppointmentManager/Views/Doctors/Create.cshtml
EasyAppointmentManager/Views/Doctors/Delete.cshtml
EasyAppointmentManager/Views/Doctors/Details.cshtml
EasyAppointmentManager/Views/Doctors/Edit.cshtml
EasyAppointmentManager/Views/Doctors/Index.cshtml
EasyAppointmentManager/Views/Services/Create.cshtml
EasyAppointmentManager/Views/Services/Delete.cshtml
EasyAppointmentManager/Views/Services/Edit.cshtml
EasyAppointmentManager/Views/Services/Index.cshtml
EasyAppointmentManager/Views/Shared/_Layout.cshtml
EasyAppointmentManager/Views/Specialties/Create.cshtml
EasyAppointmentManager/Views/Specialties/Delete.cshtml
EasyAppointmentManager/Views/Specialties/Details.cshtml
EasyAppointmentManager/Views/Specialties/Edit.cshtml
EasyAppointmentManager/Views/Specialties/Index.cshtml
EasyAppointmentManager/Views/TimeSlots/Create.cshtml
EasyAppointmentManager/Views/TimeSlots/Delete.cshtml
EasyAppointmentManager/Views/TimeSlots/Edit.cshtml
EasyAppointmentManager/Views/TimeSlots/Index.cshtml

Edited some wording to make consistent content throughout the views

---

EasyAppointmentManager/Controllers/ClinicsController.cs
EasyAppointmentManager/Controllers/CustomersController.cs
EasyAppointmentManager/Controllers/DoctorsController.cs
EasyAppointmentManager/Controllers/ServicesController.cs
EasyAppointmentManager/Controllers/SpecialtiesController.cs
EasyAppointmentManager/Controllers/TimeSlotsController.cs

Closes #78 
User who are either not logged in, or not a admin will not be able to normally access all pages except for the home page.

Restricted access to all pages except home page for non-admin users

---

EasyAppointmentManager/Controllers/ClinicsController.cs
EasyAppointmentManager/Controllers/CustomersController.cs
EasyAppointmentManager/Controllers/DoctorsController.cs
EasyAppointmentManager/Controllers/HomeController.cs
EasyAppointmentManager/Controllers/ServicesController.cs
EasyAppointmentManager/Controllers/SpecialtiesController.cs
EasyAppointmentManager/Controllers/TimeSlotsController.cs
EasyAppointmentManager/Views/Home/Index.cshtml
EasyAppointmentManager/appsettings.json

Closes #97 
I have implemented a weather API for our home index page.
This is the weather API source website:
https://www.visualcrossing.com/

Campbell issue#97 implement weather API

---

EasyAppointmentManager/Controllers/CustomerAppointmentsController.cs
EasyAppointmentManager/Controllers/ServicesController.cs
EasyAppointmentManager/Controllers/TimeSlotsController.cs
EasyAppointmentManager/Models/Clinic.cs
EasyAppointmentManager/Models/Customer.cs
EasyAppointmentManager/Models/CustomerAppointment.cs
EasyAppointmentManager/Models/CustomerCatalogViewModel.cs
EasyAppointmentManager/Models/Doctor.cs
EasyAppointmentManager/Models/IdentityHelper.cs
EasyAppointmentManager/Views/CustomerAppointments/Create.cshtml
EasyAppointmentManager/Views/Customers/Edit.cshtml

Closed #100 
Removed commented out code.
Reviewed documentation and edited/added when necessary.

Campbell issue#100 remove commented code and review documentation
